// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Chingizkhan/url-shortener/internal/domain"
	dto "github.com/Chingizkhan/url-shortener/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// ShorteningService is an autogenerated mock type for the ShorteningService type
type ShorteningService struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ShorteningService) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenerateShortenUrl provides a mock function with given fields: ctx, in
func (_m *ShorteningService) GenerateShortenUrl(ctx context.Context, in dto.ShortenURLIn) (string, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GenerateShortenUrl")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ShortenURLIn) (string, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.ShortenURLIn) string); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.ShortenURLIn) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, id
func (_m *ShorteningService) Get(ctx context.Context, id string) (domain.Shortening, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Shortening
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Shortening, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Shortening); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Shortening)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRedirectLink provides a mock function with given fields: ctx, id
func (_m *ShorteningService) GetRedirectLink(ctx context.Context, id string) (dto.RedirectURLOut, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRedirectLink")
	}

	var r0 dto.RedirectURLOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (dto.RedirectURLOut, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) dto.RedirectURLOut); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(dto.RedirectURLOut)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx
func (_m *ShorteningService) List(ctx context.Context) ([]domain.Shortening, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Shortening
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Shortening, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Shortening); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Shortening)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewShorteningService creates a new instance of ShorteningService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShorteningService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShorteningService {
	mock := &ShorteningService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
